import streamlit as st
import numpy as np
import joblib

# ==========================================================
# PAGE CONFIG
# ==========================================================

st.set_page_config(
    page_title="Diagnosis",
    page_icon="🩺",
    layout="wide"
)

# ==========================================================
# LOAD MODEL
# ==========================================================

model = joblib.load("models/diagnosis_model_clean8.pkl")
threshold = joblib.load("models/threshold_clean8.pkl")
genes = joblib.load("models/final_clean_8_genes.pkl")


# ==========================================================
# CSS
# ==========================================================

st.markdown("""
<style>

#MainMenu{
    visibility:hidden;
}

header{
    visibility:hidden;
}

footer{
    visibility:hidden;
}

.stApp{
    background:#F6F8FC;
}

.block-container{
    max-width:1200px;
    padding-top:2rem;
    padding-bottom:2rem;
}

.page-title{
    font-size:44px;
    font-weight:700;
    color:#154C97;
    margin-bottom:6px;
}

.page-subtitle{
    color:#64748B;
    font-size:18px;
    margin-bottom:35px;
    line-height:1.8;
}

.section-title{
    font-size:28px;
    font-weight:700;
    color:#154C97;
    margin-top:25px;
    margin-bottom:18px;
}

</style>
""", unsafe_allow_html=True)


# ==========================================================
# HEADER
# ==========================================================

st.markdown("""
<div class="page-title">

🩺 Diagnosis

</div>

<div class="page-subtitle">

Predict the probability of <b>Systemic Lupus Erythematosus (SLE)</b>
using the eight-gene transcriptomic diagnostic signature developed in this study.

</div>
""", unsafe_allow_html=True)


# ==========================================================
# INSTRUCTIONS
# ==========================================================

with st.expander("ℹ️ Instructions for Use", expanded=True):

    st.markdown("""

### About this Diagnostic Model

This application implements the **eight-gene transcriptomic diagnostic model**
developed in this study for identifying **Systemic Lupus Erythematosus (SLE)**.

### Model Output

- The model performs **binary classification** only.

- The two prediction classes are:

    - **0 = Healthy Control**
    - **1 = Systemic Lupus Erythematosus (SLE)**

- The displayed probabilities are the **classification probabilities**
generated by the Logistic Regression model.

- These probabilities **do not represent an individual's clinical risk,
future likelihood of developing SLE, or disease severity.**

For example:

- An **SLE Probability of 0%** indicates that the submitted transcriptomic
profile closely resembles the Healthy Control class learned during model training.

- Likewise, an **SLE Probability of 100%** indicates that the expression
profile closely resembles the SLE samples used during model development.

### Input Requirements

The model expects **normalized gene expression values** generated using
the same preprocessing workflow employed during model development.

The eight biomarkers required are:

- IFI27
- ZBP1
- SCRN1
- ABCB1
- CDCA7
- GADD45A
- TFDP1
- KLHDC8B

Entering arbitrary numerical values may produce predictions that are
not biologically meaningful.

### Expected Biomarker Expression Pattern

Although no fixed cutoff exists for individual biomarkers,
the SLE cohort used in this study generally demonstrated:

- ↑ IFI27
- ↑ ZBP1
- ↑ SCRN1
- ↑ CDCA7
- ↑ GADD45A
- ↓ ABCB1

TFDP1 and KLHDC8B contribute to the multivariate prediction model
but should not be interpreted independently.

The final prediction is generated from the **combined expression
profile of all eight biomarkers**, rather than any single gene.

### Research Note

This web application reproduces the diagnostic model exactly as developed
during this study. The displayed probabilities correspond to the model's
binary classification confidence and are presented for research purposes only.

""")
# ==========================================================
# GENE EXPRESSION INPUT
# ==========================================================

st.markdown("""
<div class="section-title">

🧬 Gene Expression Input

</div>
""", unsafe_allow_html=True)

st.info(
    """
Enter the **normalized gene expression values** for the eight diagnostic biomarkers.

**Note:** The model was trained using normalized transcriptomic data from publicly available GEO datasets. The entered values should therefore correspond to normalized gene expression measurements generated using a comparable preprocessing workflow. Arbitrary values may produce predictions that are not biologically meaningful.
"""
)

col1, col2 = st.columns(2)

with col1:

    ifi27 = st.text_input(
        "IFI27",
        placeholder="e.g. 2.145"
    )

    scrn1 = st.text_input(
        "SCRN1",
        placeholder="e.g. 0.823"
    )

    cdca7 = st.text_input(
        "CDCA7",
        placeholder="e.g. -1.247"
    )

    tfdp1 = st.text_input(
        "TFDP1",
        placeholder="e.g. 0.654"
    )

with col2:

    zbp1 = st.text_input(
        "ZBP1",
        placeholder="e.g. 1.982"
    )

    abcb1 = st.text_input(
        "ABCB1",
        placeholder="e.g. -0.512"
    )

    gadd45a = st.text_input(
        "GADD45A",
        placeholder="e.g. 0.341"
    )

    klhdc8b = st.text_input(
        "KLHDC8B",
        placeholder="e.g. -0.876"
    )

st.markdown("<br>", unsafe_allow_html=True)

predict = st.button(
    "🧬 Analyze Sample",
    use_container_width=True,
    type="primary"
)
# ==========================================================
# PREDICTION
# ==========================================================

if predict:

    try:

        # =====================================================
        # CREATE INPUT ARRAY
        # =====================================================

        input_data = np.array([[
            float(ifi27),
            float(zbp1),
            float(scrn1),
            float(abcb1),
            float(cdca7),
            float(gadd45a),
            float(tfdp1),
            float(klhdc8b)
        ]])

        # =====================================================
        # MODEL PREDICTION
        # =====================================================

        probability = model.predict_proba(input_data)[0][1]

        # Apply the saved decision threshold
        prediction = 1 if probability >= threshold else 0

        # Calculate class probabilities
        sle_probability = probability * 100
        healthy_probability = (1 - probability) * 100

        st.markdown("---")

        st.markdown("""
        <div class="section-title">
        🩺 Diagnostic Report
        </div>
        """, unsafe_allow_html=True)

        # =====================================================
        # PREDICTION RESULT
        # =====================================================

        if prediction == 1:

            st.success(
                "### 🟢 Predicted Diagnosis: **Systemic Lupus Erythematosus (SLE)**"
            )

        else:

            st.info(
                "### 🔵 Predicted Diagnosis: **Healthy Control**"
            )

        # =====================================================
        # SUMMARY CARDS
        # =====================================================

        col1, col2, col3, col4 = st.columns(4)

        with col1:
            st.metric(
                "SLE Probability",
                f"{sle_probability:.2f}%"
            )

        with col2:
            st.metric(
                "Healthy Probability",
                f"{healthy_probability:.2f}%"
            )

        with col3:
            st.metric(
                "Decision Threshold",
                f"{threshold:.2f}"
            )

        with col4:
            st.metric(
                "Biomarkers",
                "8 genes"
            )

        # =====================================================
        # PROBABILITY INTERPRETATION
        # =====================================================

        st.info(f"""
### ℹ️ Interpretation of Probabilities

The displayed probabilities represent the classification confidence generated by the Logistic Regression model.

- **SLE Probability:** {sle_probability:.2f}%
- **Healthy Probability:** {healthy_probability:.2f}%

The model performs **binary classification**, where:

- **0 = Healthy Control**
- **1 = Systemic Lupus Erythematosus (SLE)**

Therefore, these probabilities indicate how closely the submitted transcriptomic profile resembles each of the two classes learned during model training.

An **SLE Probability of 0%** indicates that the expression profile closely resembles the Healthy Control class and **does not imply zero clinical risk**.

Similarly, an **SLE Probability of 100%** indicates that the profile closely resembles the SLE class used during model development.

These probabilities should **not** be interpreted as disease severity, future disease risk, or the probability of developing SLE.
""")

        # =====================================================
        # CLINICAL INTERPRETATION
        # =====================================================

        st.markdown("### 📋 Clinical Interpretation")

        if prediction == 1:

            st.warning(f"""
The submitted transcriptomic profile has been classified as **Systemic Lupus Erythematosus (SLE)**.

The model assigned:

- **SLE Probability:** {sle_probability:.2f}%
- **Healthy Probability:** {healthy_probability:.2f}%

This prediction was generated using the combined expression profile of the following diagnostic biomarkers:

- IFI27
- ZBP1
- SCRN1
- ABCB1
- CDCA7
- GADD45A
- TFDP1
- KLHDC8B

The result should be interpreted alongside clinical findings and laboratory investigations.

This application is intended for research purposes only and should not be used as a standalone clinical diagnostic tool.
""")

        else:

            st.success(f"""
The submitted transcriptomic profile has been classified as a **Healthy Control**.

The model assigned:

- **SLE Probability:** {sle_probability:.2f}%
- **Healthy Probability:** {healthy_probability:.2f}%

No transcriptomic evidence supporting an SLE classification was identified by the model.

This result indicates that the submitted gene expression profile more closely resembles the Healthy Control samples used during model training.

The result should be interpreted alongside clinical findings and laboratory investigations.

This application is intended for research purposes only and should not be used as a standalone clinical diagnostic tool.
""")

        # =====================================================
        # DISCLAIMER
        # =====================================================

        st.markdown("---")

        st.caption("""
**Research Use Only**

This web application reproduces the eight-gene transcriptomic diagnostic model developed in this study.

The displayed probabilities correspond to the binary classification confidence generated by the Logistic Regression classifier and are intended solely for research and educational purposes.

The application must not be used as a standalone clinical diagnostic system.
""")

    except ValueError:

        st.error(
            "⚠️ Please enter valid numeric values for all eight biomarkers."
        )

    except Exception as e:

        st.exception(e)
